### ISSUE TITLE
No tower logs produce unsightly error 

### ISSUE THREAD

**Issue by michael-himes** [henson-josh/sos_script#1]
./asos.sh

Use -h flag to see additional options

find: ‘sosreport-*/var/log/tower’: No such file or directory
find: ‘sosreport-*/var/log/tower’: No such file or directory
find: ‘sosreport-*/var/log/tower’: No such file or directory
find: ‘sosreport-*/var/log/tower’: No such file or directory

**Comment by henson-josh** [comment]
Corrected, if not found it kicks it to /dev/null now
